# SPDX-License-Identifier: CC-BY-SA-4.0
# SPDX-FileCopyrightText: © 2022 Olaf Meeuwissen

include:
  - local: migrated/.gitlab-ci.yaml

build:
  stage: build
  needs:
    - job: migrate
      optional: true
  image: docker:cli
  services:
    - docker:dind
  before_script:
    - docker version
  script:
    - docker run --rm
             --volume $PWD:/mnt
             --workdir /mnt
             $MIGRATED_TAG ./bootstrap.sh $DEVUAN_CODENAME rootfs
    - cp -a overlay/* rootfs/$DEVUAN_CODENAME
    - tar -caf rootfs/$DEVUAN_CODENAME.tar --directory rootfs/$DEVUAN_CODENAME
          --exclude-from rootfs-excludes .
    - |
      cat <<EOF > .dockerignore
      *
      !rootfs/$DEVUAN_CODENAME.tar
      EOF
    - |
      cat <<EOF | docker build -t $TESTABLE_TAG -f - .
      FROM scratch
      ADD rootfs/$DEVUAN_CODENAME.tar /
      CMD ["bash"]
      EOF
    - docker push $TESTABLE_TAG
  variables:
    DEBIAN_CODENAME: bullseye
    DEVUAN_CODENAME: chimaera
    IMAGE_VARIANT: -slim
    CONTAINER_REGISTRY: $CI_REGISTRY_IMAGE
    TESTABLE_TAG: $CONTAINER_REGISTRY/devuan/testable:$DEVUAN_CODENAME-$CI_PIPELINE_ID
    MIGRATED_TAG: $CONTAINER_REGISTRY/devuan/migrated:$DEVUAN_CODENAME$IMAGE_VARIANT
  rules:
    - !reference [.build-rules, rules]

.build-rules:
  rules:
    - if: $CI_PIPELINE_SOURCE == "trigger" && $ACTION == "build"
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never
    - if: $CI_PIPELINE_SOURCE != "trigger"
      changes:
        - .gitlab-ci.yaml
        - bootstrap.sh
        - rootfs-excludes
        - overlay/**/*

test:
  stage: test
  needs:
    - job: build
  image: $TESTABLE_TAG
  script:
    - apt-get update
    - apt-get install hello
  variables:
    DEVUAN_CODENAME: chimaera
    CONTAINER_REGISTRY: $CI_REGISTRY_IMAGE
    TESTABLE_TAG: $CONTAINER_REGISTRY/devuan/testable:$DEVUAN_CODENAME-$CI_PIPELINE_ID
  rules:
    - !reference [.build-rules, rules]

deploy:
  stage: deploy
  needs:
    - job: test
  image: docker:cli
  services:
    - docker:dind
  before_script:
    - docker pull $TESTED_TAG
    - TIMESTAMP=$(date -u +%F)
  script:
    - docker tag  $TESTED_TAG $IMAGE_BASE:$DEVUAN_CODENAME-$TIMESTAMP
    - docker push --quiet     $IMAGE_BASE:$DEVUAN_CODENAME-$TIMESTAMP
    - docker tag  $TESTED_TAG $IMAGE_BASE:$DEVUAN_CODENAME
    - docker push --quiet     $IMAGE_BASE:$DEVUAN_CODENAME
    - docker tag  $TESTED_TAG $IMAGE_BASE:$DEVUAN_SUITE
    - docker push --quiet     $IMAGE_BASE:$DEVUAN_SUITE
    - |
      if test "$DEVUAN_SUITE" = "stable"; then
          docker tag  $TESTED_TAG $IMAGE_BASE:latest
          docker push --quiet     $IMAGE_BASE:latest
      fi
  variables:
    DEVUAN_CODENAME: chimaera
    DEVUAN_SUITE: stable
    CONTAINER_REGISTRY: $CI_REGISTRY_IMAGE
    TESTED_TAG: $CONTAINER_REGISTRY/devuan/testable:$DEVUAN_CODENAME-$CI_PIPELINE_ID
    IMAGE_BASE: $CONTAINER_REGISTRY/devuan
  rules:
    - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH
      when: never
    - !reference [.build-rules, rules]

# Note: The TRIGGER_TOKEN is set via CI/CD Variables.  It should only
# be set on protected branches and masked to keep it out of job logs.
check-upgradability:
  stage: test
  image: $DEPLOYED_IMAGE
  script:
    - apt-get --quiet update
    - |
      if test 0 -lt "$(apt list --upgradable 2>/dev/null \
                           | grep upgradable | wc -l)"; then
          apt-get --quiet install curl ca-certificates \
                  --assume-yes --no-install-recommends
          curl --request POST \
               --form token="$TRIGGER_TOKEN" \
               --form ref="$CI_DEFAULT_BRANCH" \
               --form "variables[ACTION]=build" \
               "$CI_API_V4_URL/projects/$CI_PROJECT_ID/trigger/pipeline"
      fi
  variables:
    DEVUAN_CODENAME: chimaera
    CONTAINER_REGISTRY: $CI_REGISTRY_IMAGE
    IMAGE_BASE: $CONTAINER_REGISTRY/devuan
    DEPLOYED_TAG: $IMAGE_BASE:$DEVUAN_CODENAME
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
