# SPDX-License-Identifier: CC-BY-SA-4.0
# SPDX-FileCopyrightText: © 2023 Olaf Meeuwissen

deprecation-warning:
  image: busybox
  stage: .pre
  script:
    - |
      cat <<EOF
      CI/CD support has moved to .gitlab/ci.yaml.  Please adjust the
      CI/CD configuration file setting in Settings » CI/CD » General
      pipelines to get rid of this job's warning.
      EOF
    - exit 1
  allow_failure: true

include:
  - local: .gitlab/ci.yaml
