# SPDX-License-Identifier: CC-BY-SA-4.0
# SPDX-FileCopyrightText: © 2022 Olaf Meeuwissen

include:
  - local: migrated/.gitlab-ci.yaml

build:
  stage: build
  needs:
    - job: migrate
  image: docker:cli
  services:
    - docker:dind
  before_script:
    - docker version
  script:
    - docker run --rm
             --volume $PWD:/mnt
             --workdir /mnt
             $BUILD_ENVIRONMENT ./bootstrap.sh $DEVUAN_CODENAME rootfs
    - tar -caf rootfs/$DEVUAN_CODENAME.tar --directory rootfs/$DEVUAN_CODENAME
          --exclude-from rootfs-excludes .
    - tar -raf rootfs/$DEVUAN_CODENAME.tar --directory overlay .
    - |
      cat <<EOF > .dockerignore
      *
      !rootfs/$DEVUAN_CODENAME.tar
      EOF
    - |
      cat <<EOF | docker build -t $CONTAINER_REGISTRY/devuan:$DEVUAN_CODENAME -f - .
      FROM scratch
      ADD rootfs/$DEVUAN_CODENAME.tar /
      CMD ["bash"]
      EOF
    - docker push $CONTAINER_REGISTRY/devuan:$DEVUAN_CODENAME
  variables:
    DEBIAN_CODENAME: bullseye
    DEVUAN_CODENAME: chimaera
    IMAGE_VARIANT: -slim
    CONTAINER_REGISTRY: $CI_REGISTRY_IMAGE
    BUILD_ENVIRONMENT: $CONTAINER_REGISTRY/devuan/migrated:$DEVUAN_CODENAME$IMAGE_VARIANT
