# SPDX-License-Identifier: CC-BY-SA-4.0
# SPDX-FileCopyrightText: © 2022 Olaf Meeuwissen

# Note: Path names are relative to the project's top-level directory.

migrate:
  stage: build
  image: docker:cli
  services:
    - docker:dind
  before_script:
    - docker version
  script:
    - docker build
          --build-arg DEBIAN_CODENAME
          --build-arg DEVUAN_CODENAME
          --build-arg IMAGE_VARIANT
          --tag $MIGRATED_TAG
          migrated
    - TIMESTAMP=$(date -u +%F)
    - docker tag $MIGRATED_TAG $MIGRATED_TAG-$TIMESTAMP
    - docker push --quiet      $MIGRATED_TAG-$TIMESTAMP
    - docker push --quiet      $MIGRATED_TAG
    - docker tag $MIGRATED_TAG $IMAGE_BASE:$DEVUAN_SUITE$IMAGE_VARIANT
    - docker push --quiet      $IMAGE_BASE:$DEVUAN_SUITE$IMAGE_VARIANT
    - |
      : ${IMAGE_VARIANT:=latest}
      if test "$DEVUAN_SUITE" = "stable"; then
          docker tag $MIGRATED_TAG $IMAGE_BASE:${IMAGE_VARIANT#-}
          docker push --quiet      $IMAGE_BASE:${IMAGE_VARIANT#-}
      fi
  parallel:
    matrix:
      - DEBIAN_CODENAME: sid
        DEVUAN_CODENAME: ceres
        DEVUAN_SUITE: unstable
      - DEBIAN_CODENAME: bookworm
        DEVUAN_CODENAME: daedalus
        DEVUAN_SUITE: testing
      - DEBIAN_CODENAME: bullseye
        DEVUAN_CODENAME: chimaera
        DEVUAN_SUITE: stable
      - DEBIAN_CODENAME: buster
        DEVUAN_CODENAME: beowulf
        DEVUAN_SUITE: oldstable
      - DEBIAN_CODENAME: stretch
        DEVUAN_CODENAME: ascii
        DEVUAN_SUITE: oldoldstable
  variables:
    IMAGE_VARIANT: -slim
    CONTAINER_REGISTRY: $CI_REGISTRY_IMAGE
    IMAGE_BASE: $CONTAINER_REGISTRY/devuan/migrated
    MIGRATED_TAG: $IMAGE_BASE:$DEVUAN_CODENAME$IMAGE_VARIANT
  rules:
    - if: $CI_PIPELINE_SOURCE == "trigger" && $ACTION == "migrate" && $CODENAME == $DEVUAN_CODENAME
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never
    - if: $CI_PIPELINE_SOURCE != "trigger"
      changes:
        - .gitlab-ci.yaml
        - migrated/**/*

# Note: The TRIGGER_TOKEN is set via CI/CD Variables.  It should only
# be set on protected branches and masked to keep it out of job logs.
check-migrated-upgradability:
  stage: test
  image: $MIGRATED_TAG
  script:
    - apt-get --quiet update
    - |
      if test 0 -lt "$(apt list --upgradable 2>/dev/null \
                           | grep upgradable | wc -l)"; then
          apt-get --quiet install curl ca-certificates \
                  --assume-yes --no-install-recommends
          curl --request POST \
               --form token="$TRIGGER_TOKEN" \
               --form ref="$CI_DEFAULT_BRANCH" \
               --form "variables[ACTION]=migrate" \
               --form "variables[CODENAME]=$DEVUAN_CODENAME" \
               "$CI_API_V4_URL/projects/$CI_PROJECT_ID/trigger/pipeline"
      fi
  parallel:
    matrix:
      - DEVUAN_CODENAME:
          - ceres
          - daedalus
          - chimaera
          - beowulf
          - ascii
  variables:
    IMAGE_VARIANT: -slim
    CONTAINER_REGISTRY: $CI_REGISTRY_IMAGE
    IMAGE_BASE: $CONTAINER_REGISTRY/devuan/migrated
    MIGRATED_TAG: $IMAGE_BASE:$DEVUAN_CODENAME$IMAGE_VARIANT
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
