# SPDX-License-Identifier: CC-BY-SA-4.0
# SPDX-FileCopyrightText: © 2022, 2023 Olaf Meeuwissen

# Note: Path names are relative to the project's top-level directory.

migrate:
  stage: build
  image: docker:cli
  services:
    - docker:dind
  before_script:
    - docker version
  script:
    - docker build
          --build-arg DEBIAN_CODENAME
          --build-arg DEVUAN_CODENAME
          --tag $MIGRATED_TAG
          migrated
    - docker push --quiet $MIGRATED_TAG
    - ./publish.sh migrated
  parallel:
    matrix:
      - DEBIAN_CODENAME: sid
        DEVUAN_CODENAME: ceres
        DEVUAN_SUITE: unstable
      - DEBIAN_CODENAME: bookworm
        DEVUAN_CODENAME: daedalus
        DEVUAN_SUITE: testing
      - DEBIAN_CODENAME: bullseye
        DEVUAN_CODENAME: chimaera
        DEVUAN_SUITE: stable
      - DEBIAN_CODENAME: buster
        DEVUAN_CODENAME: beowulf
        DEVUAN_SUITE: oldstable
      - DEBIAN_CODENAME: stretch
        DEVUAN_CODENAME: ascii
        DEVUAN_SUITE: oldoldstable
  variables:
    IMAGE_BASE: $SOURCE_REGISTRY/migrated
    MIGRATED_TAG: $IMAGE_BASE:$DEVUAN_CODENAME$BUILD_VARIANT-$CI_PIPELINE_ID
    BUILD_ID: $CI_PIPELINE_ID
    BUILD_VARIANT: -slim
    SOURCE_REGISTRY: $CI_REGISTRY_IMAGE/devuan
    TARGET_REGISTRY: $CI_REGISTRY_IMAGE/devuan
  rules:
    - if: $CI_PIPELINE_SOURCE == "trigger" && $ACTION == "migrate" && $CODENAME == $DEVUAN_CODENAME
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never
    - if: $CI_PIPELINE_SOURCE != "trigger"
      changes:
        - .gitlab-ci.yaml
        - migrated/**/*

# Note: The TRIGGER_TOKEN is set via CI/CD Variables.  It should only
# be set on protected branches and masked to keep it out of job logs.
check-migrated-upgradability:
  stage: test
  image: $MIGRATED_TAG
  script:
    - |
      if ./upgradable.sh; then
          apt-get --quiet install curl ca-certificates \
                  --assume-yes --no-install-recommends
          curl --request POST \
               --form token="$TRIGGER_TOKEN" \
               --form ref="$CI_COMMIT_BRANCH" \
               --form "variables[ACTION]=migrate" \
               --form "variables[CODENAME]=$DEVUAN_CODENAME" \
               "$CI_API_V4_URL/projects/$CI_PROJECT_ID/trigger/pipeline"
      fi
  parallel:
    matrix:
      - DEVUAN_CODENAME:
          - ceres
          - daedalus
          - chimaera
          - beowulf
          - ascii
  variables:
    BUILD_VARIANT: -slim
    CONTAINER_REGISTRY: docker.io/devuan
    IMAGE_BASE: $CONTAINER_REGISTRY/migrated
    MIGRATED_TAG: $IMAGE_BASE:$DEVUAN_CODENAME$BUILD_VARIANT
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
