# SPDX-License-Identifier: CC-BY-SA-4.0
# SPDX-FileCopyrightText: © 2022 Olaf Meeuwissen

[[runners]]
  executor = "docker"
  pre_build_script = """
  mkdir -p $HOME/.docker
  echo $DOCKER_CONFIG_JSON > $HOME/.docker/config.json
  """
  [runners.docker]
    image = "hello-world"
    tls_verify = true
    privileged = true

    # This must include the value of DOCKER_CERT_PATH configured in
    # compose.yaml.
    volumes = [
      "/certs/client",
    ]
