# SPDX-License-Identifier: CC-BY-SA-4.0
# SPDX-FileCopyrightText: © 2022 Olaf Meeuwissen

services:
  registration:
    restart: 'no'
    image: gitlab/gitlab-runner:alpine
    command:
      - register
      - --non-interactive
      - --template-config
      - /etc/gitlab-runner/config.template.toml
    environment:
      - CI_SERVER_URL=${CI_SERVER_URL:-https://gitlab.com/}
      - REGISTRATION_TOKEN
    volumes:
      - ./config:/etc/gitlab-runner

  runner:
    restart: unless-stopped
    image: gitlab/gitlab-runner:alpine
    command:
      - run
    depends_on:
      registration:
        condition: service_completed_successfully
    volumes:
      - ./config:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock
