# SPDX-License-Identifier: CC-BY-SA-4.0
# SPDX-FileCopyrightText: © 2023 Olaf Meeuwissen

stages:
  - build
  - test
  - publish
  - trigger

include:
  - local: /.gitlab/pipelines/shared.yaml

migrate:
  stage: build
  image: docker:cli
  services:
    - docker:dind
  script:
    - ./migrate.sh
  extends: .registry-rules
  variables:
    DEBIAN_REGISTRY: docker.io/library
    TARGET_REGISTRY: $STAGED_REGISTRY

publish:
  stage: publish
  image: docker:cli
  services:
    - docker:dind
  script:
    - ./publish.sh migrated
  extends: .registry-rules
  variables:
    SOURCE_REGISTRY: $STAGED_REGISTRY
    TARGET_REGISTRY: $TESTED_REGISTRY

# After publishing a new migrated image, trigger a rebuild of the
# bootstrapped image(s).

trigger:
  stage: trigger
  trigger:
    include:
      - local: /.gitlab/pipelines/bootstrap.yaml
    strategy: depend
  variables:
    # Forward variable values to the triggered pipeline
    DEVUAN_CODENAME: $DEVUAN_CODENAME
    DEVUAN_SUITE:    $DEVUAN_SUITE
    BUILD_ID:        $BUILD_ID
